### ISSUE TITLE
Look Enhancement

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/Calculator#1]
### Is your feature request related to a problem? Please describe.

It's look has to be more enhanced.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anup-chandak** [comment]
Hey @AyushAgnihotri2025  can you please assign this project to me

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @chandakanup .....

**Comment by ashupandey1620** [comment]
hey @AyushAgnihotri2025 can you please assign it to me.
I will add another screen at the bottom so that overflow conditions can be managed by showing answers in terms of exponential form.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @ashupandey1620  .....

**Comment by ksh1710** [comment]
hey @AyushAgnihotri2025  can you please assign this task to me  under IWOC'23

**Comment by AyushAgnihotri2025** [comment]
> hey @AyushAgnihotri2025 can you please assign this task to me under IWOC'23

Ok you can work 👍 on it @ksh1710  .....

**Comment by AyushAgnihotri2025** [comment]
Completed #26
