### ISSUE TITLE
Dark Mode feature.

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/Calculator#10]
### Is your feature request related to a problem? Please describe.

A option for Dark Mode has to be added in the app. It will make it amazing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Interstellar07** [comment]
I can work on this, kindly assign this to me

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Interstellar07 .....

**Comment by Interstellar07** [comment]
I have initiated a PR for this issue, please consider it.

**Comment by AyushAgnihotri2025** [comment]
> I have initiated a PR for this issue, please consider it.

Yes @Interstellar07 , I have seen it, you have done a nice work. And I am merged it also..

**Comment by AyushAgnihotri2025** [comment]
Completed #14
