### ISSUE TITLE
Migrate from toasts to Popup

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/Calculator#2]
### What happened?

1. App get crashed on some Mathematical Exceptions like 0/0 etc. 
2. And also the calculations whose answer overflows the text size limit of 8 in that cases the answers should be trimmed and displayed.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Open App
2. Try to solve 0/0
3. App gets crashed
```

### Expected behavior

It should show Error on Screen or a Toast should be shown displaying `Can't divide by zero`.

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

All devices

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaranshBaniyal** [comment]
@AyushAgnihotri2025 I would like to contribute to this issue, can you please assign this to me?

**Comment by AyushAgnihotri2025** [comment]
> @AyushAgnihotri2025 I would like to contribute to this issue, can you please assign this to me?

Ok you can work 👍 on it @SaranshBaniyal  .....

**Comment by AyushAgnihotri2025** [comment]
Please join our discord for further discussions regarding it.

**Link :** https://discord.gg/Awd3y7m9

**And kindly refer to this once also :** https://bit.ly/3XYy1D4

**Comment by SaranshBaniyal** [comment]
Sure, thanks

**Comment by SaranshBaniyal** [comment]
@AyushAgnihotri2025 the app already shows a toast while performing 0/0. Are there any other changes required sir?

**Comment by AyushAgnihotri2025** [comment]
Hey @SaranshBaniyal, Yes I know it but in mostly **Samsung Devices** it is crashing so, I am thinking of to move from toast to any other thing like a popup. You can work on it, if you wish to do kindly inform me so, that I can update the issue title or will create a new one for it.

**Comment by SaranshBaniyal** [comment]
Yes I'm interested. Pls update the title of the issue

**Comment by AyushAgnihotri2025** [comment]
Completed #5
