### ISSUE TITLE
Dark mode toggle switch gets reset

### ISSUE THREAD

**Issue by amaan-lari** [AyushAgnihotri2025/Calculator#22]
### What happened?

After turning the dark mode on when the dialog is opened again to switch to light mode the toggle is in off state instead being in on state. The toggle has to be switched on and then switched off to return back to light mode.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to 'Menu' on right top corner
2. Click on 'Preferences'
3. Toggle the Switch for Dark Mode
5. Repeat the steps 1 and 2
4. See error - 'The toggle switch is in Off state'
5. Toggle the Switch back to on state - nothing happens
6. Toggle the Switch back to off state - App gets back to light mode
```

### Expected behavior

On switching to Dark Mode the toggle switch must be in on state until it is switched back again for the light mode.
Instead the toggle gets resets to off state after changing the mode

### Version

1.1.0 (Default)

### Version (If not available above)

v1.1.0

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Lenovo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amaan-lari** [comment]
@AyushAgnihotri2025  I found a bug and tried to solve it. #1 #23 #

**Comment by AyushAgnihotri2025** [comment]
> @AyushAgnihotri2025 I found a bug and tried to solve it. #1 #23 #

Thanks @amaan-lari for finding out the bug, great work 👍

**Comment by AyushAgnihotri2025** [comment]
Hey @amaan-lari, 
Have you made this pull under IWoC'23 so, that I can add the suitable label this your pull and issue.

**Comment by AyushAgnihotri2025** [comment]
Completed #23

**Comment by amaan-lari** [comment]
> Hey @amaan-lari, Have you made this pull under IWoC'23 so, that I can add the suitable label this your pull and issue.

Yess @AyushAgnihotri2025
