### ISSUE TITLE
Add Version Control over different version of Android.

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/Calculator#24]
### Is your feature request related to a problem? Please describe.

Like for many devices it gives it a scroll view which doesn't looks good. So, Version Control should be added for different version of Android.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ksh1710** [comment]
hey @AyushAgnihotri2025, can you please assign this task to me? I have made some changes and tried and tested those changes on different devices of different android versions and it's working fine.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @ksh1710 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #32
