### ISSUE TITLE
Update README images according to app current version.

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/Calculator#25]
### Is your feature request related to a problem? Please describe.

README is using the old images of app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
Hello Sir , I want to work on this issue .
I can design the templates for the newer version of the application .

**Comment by ksh1710** [comment]
hey @AyushAgnihotri2025 can you please assign this task to me under IWOC'23 also ill make that hamburger menu correction that you mentioned earlier in the issue #26

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @ksh1710 .....

**Comment by AyushAgnihotri2025** [comment]
Hey, I have made a separate issue for the hamburger menu #27 kindly once comment there also so that I can assign that also to you.

**Comment by AyushAgnihotri2025** [comment]
Completed #32
