### ISSUE TITLE
Incorrect Hamburger Menu color in Dark Mode

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/Calculator#27]
### What happened?

The Hamburger menu color isn't matching with the dark theme. It should be fixed.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Open app
2. Click on theme toggle button
3. Switch to dark theme
4. See the unmatchable hamburger menu color in it.
```

### Expected behavior

It should have a matching color with the theme.

### Screenshots

![217608036-7634e2b3-56e7-445f-af68-4eade396daa8](https://user-images.githubusercontent.com/106915790/217699064-de1c41e6-49de-4ace-ad93-1f15b5126d2b.jpg)

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Every Device

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ksh1710** [comment]
Hey @AyushAgnihotri2025 can u please assign this task to me.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @ksh1710 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #29
