### ISSUE TITLE
Adding a backspace button 

### ISSUE THREAD

**Issue by TheNPDev** [AyushAgnihotri2025/Calculator#28]
### Is your feature request related to a problem? Please describe.

If users want to delete only the current entered number then they cannot do it by the current version of the app.

### Describe the solution you'd like

I will add a button of backspace into it.

### Additional context

I will also improve UI according to the new button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
@AyushAgnihotri2025  Please review this feature request and if you also think that it is necessary in the app then please assign it to me under IWOC label.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @TheNPDev .....

**Comment by AyushAgnihotri2025** [comment]
Completed #31
