### ISSUE TITLE
Bringing all the buttons to the bottom of the screen

### ISSUE THREAD

**Issue by UjjwalMahar** [AyushAgnihotri2025/Calculator#30]
### Is your feature request related to a problem? Please describe.

![Screenshot_2023-02-10-13-54-57-958_com mrayush calculator](https://user-images.githubusercontent.com/111011580/218041183-572d4287-a17f-4620-b37c-933b17894240.jpg)

All the buttons are shifted up.

### Describe the solution you'd like

Bringing all the buttons to the bottom of the screen may increase the overall look of the app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ksh1710** [comment]
Hey @UjjwalMahar @AyushAgnihotri2025 @ashupandey1620 i have already resolved this issue in my recent PR closing the issue #24. Please refer that.

**Comment by UjjwalMahar** [comment]
Alright 😇

**Comment by AyushAgnihotri2025** [comment]
Hey @UjjwalMahar, 
As it has been already fixed with #24 so, I am closing the issue. You can work on other issue.

Thanks for showing interest towards the repo 💖.
