### ISSUE TITLE
Sharing the banner of the app

### ISSUE THREAD

**Issue by TheNPDev** [AyushAgnihotri2025/Calculator#33]
### Is your feature request related to a problem? Please describe.

On sharing the app by clicking the share button , it only share the link of the google play store.

### Describe the solution you'd like

- I will make a banner of the app.
- By writing the external storage of the phone , we can also share that banner.
- Along with the text and link.
- It will give the idea of the app to the users.

![image](https://user-images.githubusercontent.com/105795800/218242995-bf123180-582f-4873-be95-67bd547f2c5a.png)
Current share message

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
@AyushAgnihotri2025 Please review the issue and assign it to me under IWOC label.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @TheNPDev .....

**Comment by TheNPDev** [comment]
@AyushAgnihotri2025  Please assign me this issue.

**Comment by AyushAgnihotri2025** [comment]
Ohh so sorry @TheNPDev, forgot to do so.

**Comment by AyushAgnihotri2025** [comment]
Completed #35
