### ISSUE TITLE
The app crashes when we input a negative value while doing factorial.

### ISSUE THREAD

**Issue by sidd5142** [AyushAgnihotri2025/Calculator#34]
### What happened?

The app crashes when we input a negative value while doing factorial.
It should give an error or 0 when we assign a negative value.

### Reproduction steps

```bash
Assign a negative value and find its factorial.
```

### Expected behavior

It should give an error or 0 when we assign a negative a value.

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Pixel 4 , 11 , 1080*2280

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyushAgnihotri2025** [comment]
Hey @sidd5142,
Thanks for finding 💝 out the bug, we will surely fix it in our upcoming release.

**Comment by sidd5142** [comment]
Hey @AyushAgnihotri2025   can u please assign me this task under IWOC label.

**Comment by AyushAgnihotri2025** [comment]
Ok @sidd5142, I am assigning this issue to you. You can work on it 👍.

**Comment by AyushAgnihotri2025** [comment]
Completed #37
