### ISSUE TITLE
Adding new operator and fixing existing operator

### ISSUE THREAD

**Issue by TheNPDev** [AyushAgnihotri2025/Calculator#36]
### Is your feature request related to a problem? Please describe.

- Operator Ln button works only with secondProcessingNumber , so it shows 0 as output if we only enter firstProcessingNumber .
Also there are no need of secondProcessingNumber for Ln operation.
- AC and backspace button are so far from eachother.
- There are not any operator button of Square root.

### Describe the solution you'd like

- I will fix the Ln operator button.
- AC and backspace button are same type of button . So, I will make them adjacent to each other.
- Also change their color to red.
- I will also add a new operator button of square root.
- I will modify the UI according to the changes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
Hey @AyushAgnihotri2025 , Please review this issue and assign it to me under IWOC label.

**Comment by AyushAgnihotri2025** [comment]
Ok @TheNPDev, You can work on it. 👍

**Comment by AyushAgnihotri2025** [comment]
Completed #43
