### ISSUE TITLE
Slight Vibration on click the button

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#4]
Hello @AyushAgnihotri2025 ,
I want to add the vibration effect to this calculator application. So that, users feel satisfaction with button clicks. 
Please Assign this issue to me.
Thank you.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Suryansh1720001 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #7
