### ISSUE TITLE
🪲 BUG: Incompatible version (AGP 7.4.1)

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#40]
### What happened?

Hello @AyushAgnihotri2025 

When I build this project, I come to know about this bug - This application is built with 7.4.1 which is incompatible with some laptops.
📜Following my research, I discovered that this version is compatible with the Gradle file process.
- My goal is to eliminate this bug to enable anyone to open this code and make the necessary modifications.

Kindly assign this issue to me under the event of IWOC.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

- This error is showing in code, not in the application. But this on one can modify the code if version is incompatible
```

### Expected behavior

CODE run and build smoothly.

### Screenshots

![image](https://user-images.githubusercontent.com/85965606/219896716-eb9eb077-266e-43c1-9fb8-9ce550b9c520.png)

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Asus Laptop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyushAgnihotri2025** [comment]
Ok @Suryansh1720001 , You can work on it. 👍

**Comment by Suryansh1720001** [comment]
Hello @AyushAgnihotri2025 

Kindly upgrade this issue to medium or hard. Because it is not an easy task to find a bug and it will not be resolved by simple searching. For resolving, it will take a long-long hour. So kindy upgrades it to medium or hard if you can.

**Comment by AyushAgnihotri2025** [comment]
> Hello @AyushAgnihotri2025 
> 
> Kindly upgrade this issue to medium or hard. Because it is not an easy task to find a bug and it will not be resolved by simple searching. For resolving, it will take a long-long hour. So kindy upgrades it to medium or hard if you can.

Hey @Suryansh1720001 ,
Actually I was adding the hard one but by mistake **easy** tag was added.

So sorry, for the inconvenience.

**Comment by AyushAgnihotri2025** [comment]
Completed #41

**Comment by Suryansh1720001** [comment]
Hey @AyushAgnihotri2025 
Please reopen this issue and then close it again.
The marks for this issue are currently classified as medium, but I believe they may increase if it is reevaluated as a hard-level issue.
