### ISSUE TITLE
Version Toast Message

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#42]
### Is your feature request related to a problem? Please describe.

In the slide NavigationView, when we click on version number - v1.2.0 button. It doesn't show anything.
And by this behavior of the application user may think this button has a bug. It is not good thing.

### NavigationView version number -
 <img src= "https://user-images.githubusercontent.com/85965606/220071122-b97ceb19-0906-4cae-a12b-ee532d600a24.jpg" width="250" height="505">

### Describe the solution you'd like

So, I want to fix this button and apply a toast message to it. By this Toast message, Users doesn't feel a BUG-like situation.

### Additional context

@AyushAgnihotri2025, Kindly assign this issue to me under IWOC labels with hard/medium labels.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyushAgnihotri2025** [comment]
Hey @Suryansh1720001,

Sorry but I can't mark this issue as hard, I can label it as medium as it isn't hard as much.
So, I your agree with it then kindly let me know so that I should assign it to you.

**Comment by Suryansh1720001** [comment]
Ok @AyushAgnihotri2025 no worries, then assign it to me with the medium label. 
I thought I worked on this project for a long time - KWOC and other. So, that's why I expected.

**Comment by Suryansh1720001** [comment]
Hey @AyushAgnihotri2025 
Any Update?
Assign this to me

**Comment by AyushAgnihotri2025** [comment]
> Ok @AyushAgnihotri2025 no worries, then assign it to me with the medium label. I thought I worked on this project for a long time - KWOC and other. So, that's why I expected.

Firstly, we appreciate your precious contributions in the project 💖. But if we provide a **hard** label to an issue which is of medium level, then it will be unfair with the other contributors of the project.

And each and every single contribution is important for us and we appreciate each of them. 💝

**Comment by AyushAgnihotri2025** [comment]
Hey @Suryansh1720001,

Are you working on it? Kindly let me know.

**Comment by Suryansh1720001** [comment]
@AyushAgnihotri2025 
Yes I am working on it.
I will raise the PR asap.

**Comment by Suryansh1720001** [comment]
@AyushAgnihotri2025 
I have added the PR #49 
kindly check that out.

**Comment by AyushAgnihotri2025** [comment]
Completed #49

**Comment by Suryansh1720001** [comment]
Hey @AyushAgnihotri2025 
Please reopen this issue and then close it again.
The marks for this issue are currently classified as medium, but I believe they may increase if it is reevaluated as a hard-level issue.
