### ISSUE TITLE
Source code button open sharing option

### ISSUE THREAD

**Issue by TheNPDev** [AyushAgnihotri2025/Calculator#44]
### What happened?

When user click on the source code button the app direct it to sharing option.
It does not open the github repo.

### Reproduction steps

```bash
I will use the Intent for directing the user to source code instead of sharing option.
```

### Expected behavior

On clicking the source code button , user will redirect to the github repo of the app.

### Screenshots

![WhatsApp Image 2023-02-20 at 6 06 37 PM](https://user-images.githubusercontent.com/105795800/220112495-0dc0ac2a-e7fd-4dc4-9ac3-73ede74c88c7.jpeg)

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

Vivo 1803 , 8.1.0 , 6.22''

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
Hey @AyushAgnihotri2025 , Please review this issue and assign it to me under IWOC label.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @TheNPDev .....

**Comment by AyushAgnihotri2025** [comment]
Completed #46
