### ISSUE TITLE
Adding few more operators

### ISSUE THREAD

**Issue by TheNPDev** [AyushAgnihotri2025/Calculator#45]
### Is your feature request related to a problem? Please describe.

In this calculator , there are not any trigonometric functions operator.

### Describe the solution you'd like

- I will make three new button in the app.
- First for sin , second for cos and third for tan.
- So, I will add three new operator - sin , cos and tan.
- For adding three new buttons , I have to change the UI.
- So, I will also improve the UI according to the newly added operator button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
Hey @AyushAgnihotri2025 , Please review this issue and assign it to me under IWOC label.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @TheNPDev .....

**Comment by AyushAgnihotri2025** [comment]
Completed #46
