### ISSUE TITLE
Adding different ln and log operator

### ISSUE THREAD

**Issue by TheNPDev** [AyushAgnihotri2025/Calculator#47]
### Is your feature request related to a problem? Please describe.

There are a ln button in the app but it is not ln operator , it work as log operator.
There are major difference between ln and log.

### Describe the solution you'd like

- I will change the previous ln button as log button.
- Adding a new ln operator button.
- But for this I have to do many changes in UI because now there are not any place of new button.
- I have to decrease the size of the buttons.
- I will add this new operator and some more previous operator as additional button whose size will be smaller then the previous button size.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
Hey @AyushAgnihotri2025 , Please review this issue and assign it to me under IWOC label.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @TheNPDev ......

**Comment by AyushAgnihotri2025** [comment]
Completed #51
