### ISSUE TITLE
Showing input operands and operator on screen during calculation

### ISSUE THREAD

**Issue by TheNPDev** [AyushAgnihotri2025/Calculator#48]
### Is your feature request related to a problem? Please describe.

App disappear the first processing number when we input any operator 
and it also do not show any operator on screen .

### Describe the solution you'd like

- I will make it to show all the calculations on the screen with operands and operator.
- It will disappear only when we click on equal button for answer.
- For this , I have to change the way of input of all the operands and operator.
- and also I have to change the operation of equal button.
![WhatsApp Image 2023-02-23 at 4 34 50 PM](https://user-images.githubusercontent.com/105795800/220890846-3aecef63-577b-418b-9bf6-fd7acffc55b4.jpeg)
I want that our input look like it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
Hey @AyushAgnihotri2025 , Please review this issue and assign it to me under IWOC label.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @TheNPDev .....

**Comment by AyushAgnihotri2025** [comment]
Completed https://github.com/AyushAgnihotri2025/Calculator/pull/51
