### ISSUE TITLE
Add other Language - Hindi 

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#50]
### Is your feature request related to a problem? Please describe.

Hey @AyushAgnihotri2025 

I want to make this calculator for Hindi language users also. So that they can use its features very effectively.

### Describe the solution you'd like

- add the navigation view in Hindi 
- All toast in Hindi
- All the English words that are used in the calculator will be converted into Hindi ( only sufficient English words not the calculation ones like sin, cos, and tan)

### Additional context

kindly issue this issue to me under IWOC

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
@AyushAgnihotri2025 
Any Update?

**Comment by AyushAgnihotri2025** [comment]
And sorry for the late responses as I am currently busy in my college fest [Ignitia '23](https://www.ignitia.in/).

Ok you can work 👍 on it @Suryansh1720001 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #53
