### ISSUE TITLE
Adding button of Pi and new exponential funtion operator

### ISSUE THREAD

**Issue by TheNPDev** [AyushAgnihotri2025/Calculator#52]
### Is your feature request related to a problem? Please describe.

There are not any button of pi .
Also this calculator does not have button to calculate the exponential function.

### Describe the solution you'd like

- I will add pi button.
- I will also fix its working with different operator.
- I will add an operator button of exponential function.
- Change UI accordingly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
Hey @AyushAgnihotri2025 , Please review this issue and assign it to me under IWOC.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @TheNPDev .....

**Comment by AyushAgnihotri2025** [comment]
Completed #62
