### ISSUE TITLE
🪲 [BUG]: Full content not showing in source code option

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#54]
### What happened?

When we click on the source code in the navigation bar then full content of Hindi is not showing.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to 'Navigation view'
2. Click on 'Source Code

then content in the Hindi version not showing properly.
```

### Expected behavior

I want to increase the small gap between the button of source code and the content view

### Screenshots

<img src="https://user-images.githubusercontent.com/85965606/221407037-276b1964-c48f-4a48-9ae2-009fcc9f4bf3.png">

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Android

### Additional context

Kindly assign this issue to me under IWOC

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Suryansh1720001 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #56
