### ISSUE TITLE
Add a button of "Choose Lanugage" from the internal Application

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#55]
### Is your feature request related to a problem? Please describe.

Hello @AyushAgnihotri2025 
Currently, the calculator application functions in two languages, but this is only apparent when the user's mobile is set to a specific language. To enhance usability, I plan to include a "Choose Language" button that enables users to switch between English and Hindi without any disruption to the application. This feature will be accessible from within the application, allowing users to conveniently switch between languages as per their preference.

### Additional context

Kindly, assign this issue to me under IWOC

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Suryansh1720001 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #57
