### ISSUE TITLE
adding a operator button of inverse

### ISSUE THREAD

**Issue by TheNPDev** [AyushAgnihotri2025/Calculator#58]
### Is your feature request related to a problem? Please describe.

There not any button of inverse i.e., 1/x 

### Describe the solution you'd like

- I will add a button of inverse.
- Improve UI according to new button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNPDev** [comment]
Hey @AyushAgnihotri2025  , Please review this issue and assign it to me under IWOC label.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @TheNPDev .....

**Comment by SimonShangpliang** [comment]
i guess this is done it can be taken down as well

**Comment by AyushAgnihotri2025** [comment]
Completed #92
