### ISSUE TITLE
🪲 [BUG]: Dialog for Update app reminder Irritates a lot

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#59]
### What happened?

Hey @AyushAgnihotri2025 
Each time the app's dark mode is turned on or off, a dialog box reminder to update the app appears. While it's important to update the application, it's not necessary to remind the user every time. The navigation view already provides a "Check for Update" option. 

This behavior of the application can easily irritate users, as each user has their own preference for using the app in dark or light mode. Even I find it very irritating while using the application. 

Nowadays, Play Store is so intelligent that it automatically updates the application if the functionality is enabled. For those who haven't enabled this feature, there is a "Check for Update" option in the app's prebuilt features.
We have to think about this issue from the side of the user. 

Users want a clear and simple UI, not an annoying one. Therefore, we should remove this functionality from the application.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to 'FIRST PAGE'
2. Click on 'DARK MODE ON/OFF'
3. Irritative updating remainder comes every time.
```

### Expected behavior

not annoying when dark mode on/off.

### Screenshots

https://user-images.githubusercontent.com/85965606/221431941-47ce481b-1ab0-4dbc-be3c-f3797ca459ab.mp4

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Android

### Additional context

Kindly assign me this Issue. And add on the Iwoc labels ( IWOC + Hard level).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Suryansh1720001 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #64
