### ISSUE TITLE
Vibration is not attached to some buttons 

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#61]
### Is your feature request related to a problem? Please describe.

Vibration is not added with some buttons like Choose Langauge, dark mode ON/OFF, etc.

I want to add two things-
- Vibration added to all the necessary buttons.
- add a minimal amount of vibration so that the user feels a more practical experience. 
- It feels the same when the user clicks the actual/real calculator.

### Additional context

Kindly assign me this issue under IWOC with its labels (IWOC + difficulty level).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Suryansh1720001 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #65
