### ISSUE TITLE
Adding option to see all previous Calculations History.

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/Calculator#63]
### Is your feature request related to a problem? Please describe.

Currently, the app doesn't store the calculations history. So, it will be great if there is such an option for that.

### Describe the solution you'd like

- The app should store all calculations done through it as a history and display it and also allow users to repeat those calculations by clicking on them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashupandey1620** [comment]
@AyushAgnihotri2025 Can you please Assign this Feature Enhancement to me under HacktoberFest 2023 Label, I will be saving the Calculation results up to 20 last Calculations  using stack and room DB.

**Comment by SimonShangpliang** [comment]
@AyushAgnihotri2025 Can you assign this issue to me under CodePeak 23' , i still see the same issue wherein previous calculations are not stored.

**Comment by ghost** [comment]
> @AyushAgnihotri2025 Can you assign this issue to me under CodePeak 23' , i still see the same issue wherein previous calculations are not stored.
@SimonShangpliang Okay, you can work on this issue.

**Comment by SimonShangpliang** [comment]
I have fixed the issue of storing the calculations. I figured it would not make much sense to click on them and get something, so i just made a recyclerview containing the whole list of calculations done previously, and also integrated a clear button to clear all calculation history
@AyushAgnihotri2025  @developerBugs67 
![calculationHistory](https://github.com/AyushAgnihotri2025/Calculator/assets/118509034/93cbfc30-66cb-4735-bc49-79c32354fd4a)

**Comment by SimonShangpliang** [comment]
i would like to pull this part first if you're satisfied with this

**Comment by ghost** [comment]
@SimonShangpliang Nice Work, Keep it Up!!!

**Comment by ghost** [comment]
@SimonShangpliang You can raise a Pull Request for this.
