### ISSUE TITLE
🪲 [BUG]: DayNight Mode save - Don't need to set every time

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#67]
### What happened?

Hey @AyushAgnihotri2025 

Have you noticed anything when using the DayNight feature in the application? 
Once a particular DayNight mode is applied and activated, it remains active until the user closes the app. So, if you use the calculator feature after switching to DayNight mode, the theme of the calculator will be based on the device's theme, not on the theme you saved previously. 
Then there is no meaning of showing the change theme option in internal application.
So I want to fix this issue.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to 'Front Page'
2. Change the theme 
3. Now close the application completely.
4. Now reopen it, your theme is not saved
```

### Expected behavior

The saved theme will remain in effect until we make changes to it.

### Screenshots

https://user-images.githubusercontent.com/85965606/221623283-844f3b74-64ff-4b32-ab68-affbdfe0a157.mp4

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Android

### Additional context

Kindly assign this to me with IWOC labels (IWOC + Hard level).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Suryansh1720001 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #72
