### ISSUE TITLE
🪲 [BUG]: Feedback button is not working

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#68]
### What happened?

I am unsure as to why, but upon initial installation of the application, when we click on the feedback button, it prompts us to rate the app specifically within the application. This raises two points of concern:

Firstly, if we click anywhere outside of the rating dialog, it disappears and does not reappear, even when we click the feedback button again it shows - "Thanks for the rating". This can be verified in a video, and the same behavior has been observed on other devices.

Secondly, suppose an individual rates the application, but subsequently wishes to modify their rating after a few days. In that case, how would they go about doing so?

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Expected behavior

I want that user shift to the playstore for rate the application. And for editing purpose, he/she will also shifted to the playstore.

### Screenshots

https://user-images.githubusercontent.com/85965606/221628197-cc0e3c9a-4711-4b2c-a5a4-e22f4ff9daee.mp4

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Android

### Additional context

Kindly assign this to me with IWOC labels (IWOC + Hard level)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hey @AyushAgnihotri2025 
Kindly assign this to me

**Comment by Suryansh1720001** [comment]
Hey @AyushAgnihotri2025 
Kindly assign this to me

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Suryansh1720001 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #73
