### ISSUE TITLE
Add Table of Content in Readme  ⭐

### ISSUE THREAD

**Issue by dhruv-porwal** [AyushAgnihotri2025/Calculator#74]
### Is your feature request related to a problem? Please describe.

Let's add  a Table of Content in Readme for ease of use of users.

### Describe the solution you'd like

this handy table would provide a glance at all the topics covered in the Readme file in a detailed manner.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhruv-porwal** [comment]
please assign this issue to me @AyushAgnihotri2025 under medium/hard as i would implement anchor tags on all the headings and would dynamically link it in table of contents created by me.

**Comment by dhruv-porwal** [comment]
![Screenshot (2016)](https://user-images.githubusercontent.com/73400504/221884262-1b63d71d-351b-42cb-9c36-e64efafc35c6.png)


it would look like this

**Comment by dhruv-porwal** [comment]
![Screenshot (2016)](https://user-images.githubusercontent.com/73400504/221884836-0fd7d3bc-e641-47e4-9cc6-30238f1a6a6a.png)


it would look like this sir.

**Comment by dhruv-porwal** [comment]
@AyushAgnihotri2025  I have already made a pr please merge it after assigning this issue to me under iwoc

**Comment by dhruv-porwal** [comment]
Thank you sir🙏🙏

**Comment by AyushAgnihotri2025** [comment]
Completed #78
