### ISSUE TITLE
Adding Toast for Scroll Down for the Rating

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#75]
### Is your feature request related to a problem? Please describe.

Adding the Toast after pressing the button of Rate button. So that user feels good. 
And users have a guide for how to Rate the application.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/85965606/221840422-627d7724-a067-4dde-b37e-d14702483725.png)

_No response_

### Additional context

**Kindly assign this issue to me under IWOC labels with MEDIUM level.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hey @AyushAgnihotri2025 
I have raised PR #76.
Kindly check and merge that.

**Comment by AyushAgnihotri2025** [comment]
Completed #76
