### ISSUE TITLE
Add Button of "Report Bug 🪲" for real-time users

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#77]
### Is your feature request related to a problem? Please describe.

Hey @AyushAgnihotri2025 ,

My intention is to include a button within the application that enables users to report any bugs they encounter. Upon clicking this button, they will be able to send you an email outlining the issue, whether it be an error in the calculator or something else. This presents an opportunity for us to receive bug reports from users in real time, as they have a firsthand experience of the application's performance. 
This presents an opportunity for us to receive bug reports from users in real time, as they have a firsthand experience of the application's performance.

### Additional context

**Kindly assign this issue to me under IWOC with (IWOC + Hard level) labels.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
I have raised the PR #79, kindly merge that.

**Comment by AyushAgnihotri2025** [comment]
Completed #79
