### ISSUE TITLE
Add soft sound when click on functionalities buttons

### ISSUE THREAD

**Issue by Suryansh1720001** [AyushAgnihotri2025/Calculator#8]
### Is your feature request related to a problem? Please describe.

I will add a soft sound that fell satisfaction after clicking the functionalities button. 
Kindly assign it to me.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Suryansh1720001 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #12
