### ISSUE TITLE
App  is crashing on pushing +/- button after applying any function.

### ISSUE THREAD

**Issue by ashupandey1620** [AyushAgnihotri2025/Calculator#81]
### What happened?

1. Go to app Main Screen
2. Click on Any function Button
3. Click on +/- button

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Expected behavior

we can neglect +/- button setOnClicklistner when an function is already in stack.

### Screenshots

App Crashing

### Version

1.1.0 (Default)

### Version (If not available above)

v1.3.0

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

oppo A7

### Additional context

App Crashing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashupandey1620** [comment]
@AyushAgnihotri2025 Can you please Assign this Feature Enhancement to me under HacktoberFest 2023 Label, I will be changing the Backend features of the code so that this issue can be resolved.

**Comment by ghost** [comment]
@ashupandey1620 you can work on this.
