### ISSUE TITLE
Creating an Animated Splash Screen for the App.

### ISSUE THREAD

**Issue by ashupandey1620** [AyushAgnihotri2025/Calculator#82]
### Is your feature request related to a problem? Please describe.

A splash screen (also known as a launch or startup screen) is the first screen you see when you open your application.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashupandey1620** [comment]
@AyushAgnihotri2025 Can you please Assign this Feature Enhancement to me under HacktoberFest 2023 Label, I will Add a Splash Screen with Compose UI in the App.

**Comment by PIYUSH-69** [comment]
can you assign me this issue @AyushAgnihotri2025

**Comment by AyushAgnihotri2025** [comment]
@PIYUSH-69 Yes you can work on this.

**Comment by ashupandey1620** [comment]
@AyushAgnihotri2025 @developerBugs67 please review my pull request.
