### ISSUE TITLE
Creating an Animated Onboarding Screen for the App which help user to get Started with the App.

### ISSUE THREAD

**Issue by ashupandey1620** [AyushAgnihotri2025/Calculator#83]
### Is your feature request related to a problem? Please describe.

Onboarding is a virtual unboxing experience that helps users get started with an app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashupandey1620** [comment]
@AyushAgnihotri2025 Can you please Assign this Feature Enhancement to me under HacktoberFest 2023 Label, I will Add an Onboarding Screen with Compose UI in the App.

**Comment by AyushAgnihotri2025** [comment]
Okay you can work for it. @ashupandey1620
