### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by ashupandey1620** [AyushAgnihotri2025/Calculator#84]
### What happened?

There are some Logical Bugs in the App.
1. Some Toast messages are occurring in the App in the opening of the App.
2. Some UI/UX bugs exist where the buttons are not seen as clickable.
and some Recommended color changes.

### Reproduction steps

```bash
Start the App, A Toast message will occur at splash Screen of the App.
```

### Expected behavior

It should not occur as Toast message are for development purpose and if any toast is used then it should be replaced with dialog msg.

### Version

1.1.0 (Default)

### Version (If not available above)

v1.2.0

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

Samsung A7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashupandey1620** [comment]
@AyushAgnihotri2025 Can you please Assign this Feature Enhancement to me under HacktoberFest 2023 Label, I will try to fix all the Bugs.

**Comment by AyushAgnihotri2025** [comment]
Okay you can work for it. @ashupandey1620

**Comment by PIYUSH-69** [comment]
@AyushAgnihotri2025 can you assign this to me
