### ISSUE TITLE
Add options for Scientific Calculations.

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/Calculator#9]
### Is your feature request related to a problem? Please describe.

Options for Scientific Calculations has to be added in the Calculator.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashupandey1620** [comment]
I will add some Scientific feature with some additional buttons .please assign it to me.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @ashupandey1620 .....

**Comment by AyushAgnihotri2025** [comment]
Completed #18
