### ISSUE TITLE
ADD modulo and Inverse operators

### ISSUE THREAD

**Issue by SimonShangpliang** [AyushAgnihotri2025/Calculator#90]
### Is your feature request related to a problem? Please describe.

It is quite a trouble trying to perform modulo calculations without using a calculator, and its not there in normal calculator, so it would be a nice thing to add this feature. Also inverse operator is still missing

### Describe the solution you'd like

I would like to add additional buttons on the screen for these operations by decreasing size of the top buttons and adding two additional buttons

### Describe alternatives you've considered

i could add the buttons on a new row with some additional operators.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonShangpliang** [comment]
Please assign me this issue under CodePeak 23'

**Comment by SimonShangpliang** [comment]
@AyushAgnihotri2025  is this project dead?

**Comment by AyushAgnihotri2025** [comment]
@SimonShangpliang Okay, you can work on this issue.

**Comment by SimonShangpliang** [comment]
![moduloinv](https://github.com/AyushAgnihotri2025/Calculator/assets/118509034/72e0f096-25a5-4cb6-bcb0-b1c0ed189b77)

added the modulo and inv operation, it works

**Comment by SimonShangpliang** [comment]
is this fine?
@AyushAgnihotri2025  @developerBugs67

**Comment by AyushAgnihotri2025** [comment]
> is this fine? @AyushAgnihotri2025 @developerBugs67

Yes, it's fine. You can make a pull for the same.

**Comment by ghost** [comment]
@SimonShangpliang You can make a pull request for the same.

**Comment by SimonShangpliang** [comment]
i guess this is done, it can be taken down

**Comment by AyushAgnihotri2025** [comment]
Completed #92 by @SimonShangpliang
